package com.tsop.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import com.tsop.vo.*;
import com.tsop.db.ConnectDB;
import com.tsop.vo.StorageVO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StorageViewDAO.java
//  @ Date : 2018-07-17
//  @ Author : 
//
//




public class StorageViewDAO {
	
/*	public static void main(String args[]){
		StorageViewDAO dao=new StorageViewDAO();
		StorageVO vo=dao.searchStorage("donghoon");
		System.out.println(vo.toString());
		
	}*/
	
	public StorageVO searchStorage(String memberId) {

		Connection conn = 	null;
		PreparedStatement pstmt = null;
		ResultSet rs=null;
		StorageVO vo=null;
		
		try {
			conn = ConnectDB.connect();
			
			pstmt=conn.prepareStatement("select * from storage_size_view where member_id=?");
			pstmt.setString(1, memberId);
			rs=pstmt.executeQuery();
			
			rs.next();
			vo=new StorageVO(rs.getString("member_id"),rs.getInt("maximum_storage_size"),rs.getInt("total_file_size"));
			
		} catch (SQLException e) {
			e.printStackTrace();
			return null;
		}finally{
			ConnectDB.close(conn,pstmt,rs);
		}
		
		//sql�� null�� ��� 0 return;
		
		
		return vo;

	}
}
