package com.tsop.dao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import com.tsop.db.ConnectDB;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FollowDAO.java
//  @ Date : 2018-07-17
//  @ Author : 
//
//




public class FollowDAO {
	
	public String addFollow(String followId, String followerId) {
	

		Connection conn = 	null;
		PreparedStatement pstmt = null;
		
		String str=null;
		
		try {
			conn = ConnectDB.connect();
			
			pstmt=conn.prepareStatement("insert into follow_tb (follow_member_id, follower_member_id) values (?,?)");
			pstmt.setString(1, followId);
			pstmt.setString(2, followerId);
			pstmt.executeUpdate();
			
			str=followId+"/"+followerId;
			
		} catch (SQLException e) {
			e.printStackTrace();
			return null;
		}finally{
			ConnectDB.close(conn,pstmt);
		}
		
		//sql�� null�� ��� 0 return;
		
		
		return str;
		
		
	}
	
	public String deleteFollow(String followId, String followerId) {
	


		Connection conn = 	null;
		PreparedStatement pstmt = null;
		
		String str=null;
		
		try {
			conn = ConnectDB.connect();
			
			pstmt=conn.prepareStatement("delete follow_tb where follow_member_id=? and follower_member_id=?");
			pstmt.setString(1, followId);
			pstmt.setString(2, followerId);
			pstmt.executeUpdate();
			
			str=followId+"/"+followerId;
			
		} catch (SQLException e) {
			e.printStackTrace();
			return null;
		}finally{
			ConnectDB.close(conn,pstmt);
		}
		
		//sql�� null�� ��� 0 return;
		
		
		return str;
		
	}
}
