package com.tsop.dto;

import java.time.LocalDateTime;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileDTO.java
//  @ Date : 2018-07-14
//  @ Author : 
//
//




public class FileDTO {
	public int fileId;
	public int localFileId;
	public String fileName;	
	public String memberId;
	public String memberNickName;
	public LocalDateTime fileUploadDate;
	public int fileSize;
	public boolean isImportant;
	public String extension;
	public int folderId;
	public String imagePath;
	
	public FileDTO(){
		
		fileId=1;
		localFileId=1;
		fileName="avengers.mp3";
		memberId="jiwoo";
		memberNickName="jiwooGongju";
		fileUploadDate=	LocalDateTime.of(2018, 7, 15, 13, 13, 13);
		fileSize=10;
		isImportant=false;
		extension="mp3";
		folderId=1;
		imagePath="/image/1.png";
		
	}
	
	public FileDTO(int fileId, int localFileId, String fileName, String memberId, String memberNickName,
			LocalDateTime fileUploadDate, int fileSize, boolean isImportant, String extension, int folderId,
			String imagePath) {
		super();
		this.fileId = fileId;
		this.localFileId = localFileId;
		this.fileName = fileName;
		this.memberId = memberId;
		this.memberNickName = memberNickName;
		this.fileUploadDate = fileUploadDate;
		this.fileSize = fileSize;
		this.isImportant = isImportant;
		this.extension = extension;
		this.folderId = folderId;
		this.imagePath = imagePath;
	}

	public int getFileId() {
		return fileId;
	}

	public int getLocalFileId() {
		return localFileId;
	}

	public String getFileName() {
		return fileName;
	}

	public String getMemberId() {
		return memberId;
	}

	public String getMemberNickName() {
		return memberNickName;
	}

	public LocalDateTime getFileUploadDate() {
		return fileUploadDate;
	}

	public int getFileSize() {
		return fileSize;
	}

	public boolean isImportant() {
		return isImportant;
	}

	public String getExtension() {
		return extension;
	}

	public int getFolderId() {
		return folderId;
	}

	public String getImagePath() {
		return imagePath;
	}

	public void setFileId(int fileId) {
		this.fileId = fileId;
	}

	public void setLocalFileId(int localFileId) {
		this.localFileId = localFileId;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public void setMemberNickName(String memberNickName) {
		this.memberNickName = memberNickName;
	}

	public void setFileUploadDate(LocalDateTime fileUploadDate) {
		this.fileUploadDate = fileUploadDate;
	}

	public void setFileSize(int fileSize) {
		this.fileSize = fileSize;
	}

	public void setImportant(boolean isImportant) {
		this.isImportant = isImportant;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public void setFolderId(int folderId) {
		this.folderId = folderId;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}
	
	
	
	
	
}
