package com.tsop.dto;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FolderDTO.java
//  @ Date : 2018-07-14
//  @ Author : 
//
//




public class FolderDTO {
	public int folderId;
	public String folderName;
	public String folderPath;
	public String memberId;
	public String memberNickName;
	
	public FolderDTO(){
		
		folderId=1;
		folderName="dejava";
		folderPath="/jiwoo/folder/";
		memberId="jiwoo";
		memberNickName="jiwooGongju";
		
	}
	
	public FolderDTO(int folderId, String folderName, String folderPath, String memberId, String memberNickName) {
		super();
		this.folderId = folderId;
		this.folderName = folderName;
		this.folderPath = folderPath;
		this.memberId = memberId;
		this.memberNickName = memberNickName;
	}

	public int getFolderId() {
		return folderId;
	}

	public String getFolderName() {
		return folderName;
	}

	public String getFolderPath() {
		return folderPath;
	}

	public String getMemberId() {
		return memberId;
	}

	public String getMemberNickName() {
		return memberNickName;
	}

	public void setFolderId(int folderId) {
		this.folderId = folderId;
	}

	public void setFolderName(String folderName) {
		this.folderName = folderName;
	}

	public void setFolderPath(String folderPath) {
		this.folderPath = folderPath;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public void setMemberNickName(String memberNickName) {
		this.memberNickName = memberNickName;
	}
	
		
	
	
}
