package com.tsop.dto;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FollowDTO.java
//  @ Date : 2018-07-14
//  @ Author : 
//
//




public class FollowDTO {
	public String followId;
	public String followerId;
	
	public FollowDTO(){
		
		followId="jiwoo";
		followerId="yong";
	}
	
	public FollowDTO(String followId, String followerId) {
		super();
		this.followId = followId;
		this.followerId = followerId;
	}

	public String getFollowId() {
		return followId;
	}

	public String getFollowerId() {
		return followerId;
	}

	public void setFollowId(String followId) {
		this.followId = followId;
	}

	public void setFollowerId(String followerId) {
		this.followerId = followerId;
	}
	
		
	
}
