package com.tsop.dto;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LikePlaylistDTO.java
//  @ Date : 2018-07-14
//  @ Author : 
//
//




public class LikePlaylistDTO {
	public String memberId;
	public int playlistId;
	
	public LikePlaylistDTO(){
		
		memberId="jiwoo";
		playlistId=1;
		
	}

	public LikePlaylistDTO(String memberId, int playlistId) {
		super();
		this.memberId = memberId;
		this.playlistId = playlistId;
	}

	public String getMemberId() {
		return memberId;
	}

	public int getPlaylistId() {
		return playlistId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public void setPlaylistId(int playlistId) {
		this.playlistId = playlistId;
	}
	
	
	
}
