package com.tsop.dto;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberDTO.java
//  @ Date : 2018-07-14
//  @ Author : 
//
//




public class MemberDTO {
	public String memberId;
	public String memberPwd;
	public String memberNickName;
	public String memberName;
	public String imagePath;
	public String memberPhone;
	public String memberEmail;
	public String memberClassName;
	public int memberStorageSize;
	public int memberUsedSize;
	public String memberIntro;
	
	public MemberDTO(){
		
		memberId="jiwoo";
		memberPwd="1234";
		memberNickName="jiwooGongju";
		memberName="지우";
		imagePath="/image/2.jpg";
		memberPhone="01011117777";
		memberEmail="jiwoo@gmail.com";
		memberClassName="회원";
		memberStorageSize=3;
		memberUsedSize=10;
		memberIntro="집에가고싶군요";
		
	}
	
	public MemberDTO(String memberId, String memberPwd, String memberNickName, String memberName, String imagePath,
			String memberPhone, String memberEmail, String memberClassName, int memberStorageSize, int memberUsedSize,
			String memberIntro) {
		super();
		this.memberId = memberId;
		this.memberPwd = memberPwd;
		this.memberNickName = memberNickName;
		this.memberName = memberName;
		this.imagePath = imagePath;
		this.memberPhone = memberPhone;
		this.memberEmail = memberEmail;
		this.memberClassName = memberClassName;
		this.memberStorageSize = memberStorageSize;
		this.memberUsedSize = memberUsedSize;
		this.memberIntro = memberIntro;
	}

	public String getMemberId() {
		return memberId;
	}

	public String getMemberPwd() {
		return memberPwd;
	}

	public String getMemberNickName() {
		return memberNickName;
	}

	public String getMemberName() {
		return memberName;
	}

	public String getImagePath() {
		return imagePath;
	}

	public String getMemberPhone() {
		return memberPhone;
	}

	public String getMemberEmail() {
		return memberEmail;
	}

	public String getMemberClassName() {
		return memberClassName;
	}

	public int getMemberStorageSize() {
		return memberStorageSize;
	}

	public int getMemberUsedSize() {
		return memberUsedSize;
	}

	public String getMemberIntro() {
		return memberIntro;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public void setMemberPwd(String memberPwd) {
		this.memberPwd = memberPwd;
	}

	public void setMemberNickName(String memberNickName) {
		this.memberNickName = memberNickName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public void setMemberPhone(String membePhone) {
		this.memberPhone = membePhone;
	}

	public void setMemberEmail(String memberEmail) {
		this.memberEmail = memberEmail;
	}

	public void setMemberClassName(String memberClassName) {
		this.memberClassName = memberClassName;
	}

	public void setMemberStorageSize(int memberStorageSize) {
		this.memberStorageSize = memberStorageSize;
	}

	public void setMemberUsedSize(int memberUsedSize) {
		this.memberUsedSize = memberUsedSize;
	}

	public void setMemberIntro(String memberIntro) {
		this.memberIntro = memberIntro;
	}
	
	
	
}
