package com.tsop.dto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MusicDTO.java
//  @ Date : 2018-07-14
//  @ Author : 
//
//




public class MusicDTO {
	
	private static MusicDTO musicDTO;
	private int fileId;
	private int musicId;
	private String musicTitle;
	private String musicIntro;
	private String imagePath;
	private String memberId;
	private String memberNickName;
	private String genreName;
	private String tagName;
	private int likeCnt;
	private int playCnt;
	private boolean visibility;
	private boolean downloadAccept;
	
	static{
		musicDTO = new MusicDTO();
	}
	
	public MusicDTO(){
		
		fileId=1;
		musicId=1;
		musicTitle="첫차가 막차~";
		musicIntro="버스타고 가자~ 버스타면 환승도돼";
		imagePath="/image/3.png";
		memberId="jiwoo";
		memberNickName="jiwooGongju";
		genreName="Rock";
		tagName="Rock짱";
		likeCnt=0;
		playCnt = 50;
		visibility=true;
		downloadAccept=true;
		
	}
	
	public MusicDTO(int fileId, int musicId, String musicTitle,String musicIntro, String imagePath, String memberId,
			String memberNickName, String genreName, String tagName, int likeCnt, int playCnt, boolean visibility,
			boolean downloadAccept) {
		super();
		this.fileId = fileId;
		this.musicId = musicId;
		this.musicTitle = musicTitle;
		this.musicIntro = musicIntro;
		this.imagePath = imagePath;
		this.memberId = memberId;
		this.memberNickName = memberNickName;
		this.genreName = genreName;
		this.tagName = tagName;
		this.likeCnt = likeCnt;
		this.playCnt = playCnt;
		this.visibility = visibility;
		this.downloadAccept = downloadAccept;
	}
	public static MusicDTO getInstance(){return musicDTO;}
	public int getFileId() {
		return fileId;
	}

	public int getMusicId() {
		return musicId;
	}

	public String getMusicTitle() {
		return musicTitle;
	}

	public String getImagePath() {
		return imagePath;
	}

	public String getMemberId() {
		return memberId;
	}

	public String getMemberNickName() {
		return memberNickName;
	}

	public String getGenreName() {
		return genreName;
	}

	public String getTagName() {
		return tagName;
	}

	public int getLikeCnt() {
		return likeCnt;
	}

	public String getMusicIntro() {
		return musicIntro;
	}

	public void setMusicIntro(String musicIntro) {
		this.musicIntro = musicIntro;
	}

	public int getPlayCnt() {
		return playCnt;
	}

	public void setPlayCnt(int playCnt) {
		this.playCnt = playCnt;
	}

	public boolean isVisibility() {
		return visibility;
	}

	public boolean isDownloadAccept() {
		return downloadAccept;
	}

	public void setFileId(int fileId) {
		this.fileId = fileId;
	}

	public void setMusicId(int musicId) {
		this.musicId = musicId;
	}

	public void setMusicTitle(String musicTitle) {
		this.musicTitle = musicTitle;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public void setMemberNickName(String memberNickName) {
		this.memberNickName = memberNickName;
	}

	public void setGenreName(String genreName) {
		this.genreName = genreName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	public void setLikeCnt(int likeCnt) {
		this.likeCnt = likeCnt;
	}

	public void setVisibility(boolean visibility) {
		this.visibility = visibility;
	}

	public void setDownloadAccept(boolean downloadAccept) {
		this.downloadAccept = downloadAccept;
	}
	
	
	
}
