package com.tsop.dto;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PlaylistPathDTO.java
//  @ Date : 2018-07-14
//  @ Author : 
//
//




public class PlaylistPathDTO {
	public int playlistId;
	public String playlistPath;
	
	public PlaylistPathDTO(){
		
		playlistId=1;
		playlistPath="/playlist/1.tsop";
		
	}
	
	public PlaylistPathDTO(int playlistId, String playlistPath) {
		super();
		this.playlistId = playlistId;
		this.playlistPath = playlistPath;
	}

	public int getPlaylistId() {
		return playlistId;
	}

	public String getPlaylistPath() {
		return playlistPath;
	}

	public void setPlaylistId(int playlistId) {
		this.playlistId = playlistId;
	}

	public void setPlaylistPath(String playlistPath) {
		this.playlistPath = playlistPath;
	}
	
		
	
}
