package com.tsop.dto;
import java.time.LocalDateTime;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PlaylistDTO.java
//  @ Date : 2018-07-14
//  @ Author : 
//
//




public class PlaylistDTO {
	public int playlistId;
	public String playlistTitle;
	public String imagePath;
	public String memberId;
	public String memberNickName;
	public String tagName;
	public String playlistIntro;
	public LocalDateTime playlistDate;
	public boolean visibility;
	
	public PlaylistDTO(){
		playlistId=1;
		playlistTitle="코카콜라";
		imagePath="/image/4.png";
		memberId="jiwoo";
		memberNickName="jiwooGongju";
		tagName="사이다";
		playlistIntro="시원하쥬?";
		playlistDate=LocalDateTime.of(2018,7,15,0,13,23);
		visibility=true;
	}
	
	public PlaylistDTO(int playlistId, String playlistTitle, String imagePath, String memberId, String memberNickName,
			String tagName, String playlistIntro, LocalDateTime playlistDate, boolean visibility) {
		super();
		this.playlistId = playlistId;
		this.playlistTitle = playlistTitle;
		this.imagePath = imagePath;
		this.memberId = memberId;
		this.memberNickName = memberNickName;
		this.tagName = tagName;
		this.playlistIntro = playlistIntro;
		this.playlistDate = playlistDate;
		this.visibility = visibility;
	}

	public int getPlaylistId() {
		return playlistId;
	}

	public String getPlaylistTitle() {
		return playlistTitle;
	}

	public String getImagePath() {
		return imagePath;
	}

	public String getMemberId() {
		return memberId;
	}

	public String getMemberNickName() {
		return memberNickName;
	}

	public String getTagName() {
		return tagName;
	}

	public String getPlaylistIntro() {
		return playlistIntro;
	}

	public LocalDateTime getPlaylistDate() {
		return playlistDate;
	}

	public boolean isVisibility() {
		return visibility;
	}

	public void setPlaylistId(int playlistId) {
		this.playlistId = playlistId;
	}

	public void setPlaylistTitle(String playlistTitle) {
		this.playlistTitle = playlistTitle;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public void setMemberNickName(String memberNickName) {
		this.memberNickName = memberNickName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	public void setPlaylistIntro(String playlistIntro) {
		this.playlistIntro = playlistIntro;
	}

	public void setPlaylistDate(LocalDateTime playlistDate) {
		this.playlistDate = playlistDate;
	}

	public void setVisibility(boolean visibility) {
		this.visibility = visibility;
	}
	
	
	
	
	
}
